### Obtener todos los usuarios (admin)
GET http://localhost:3000/api/users
Authorization: Bearer TU_TOKEN_ADMIN

### Obtener usuario por ID (admin)
GET http://localhost:3000/api/users/ID_DE_USUARIO
Authorization: Bearer TU_TOKEN_ADMIN

### Actualizar rol de usuario (admin)
PUT http://localhost:3000/api/users/ID_DE_USUARIO
Authorization: Bearer TU_TOKEN_ADMIN
Content-Type: application/json

{
  "role": "admin"
}

### Eliminar usuario (admin)
DELETE http://localhost:3000/api/users/ID_DE_USUARIO
Authorization: Bearer TU_TOKEN_ADMIN